# Test 2023-10-22 at 06:09:58

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/SvgSimple
        path: svg

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Ubuntu update
      run:  sudo apt update

    - name: Tree
      run:
        sudo apt install tree
        tree

    - name: Test Perl
      run:
        perl -Idtt -Isvg lib/Svg/Simple.pm
