# Test 2024-04-11 at 00:53:58

name: Test

on:
  push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/DataTableText
        path: dtt

    - uses: actions/checkout@v3
      with:
        repository: philiprbrenan/MathIntersectionCircleLine
        path: micl

    - name: Cpan
      run:  sudo cpan install -T Data::Dump
    - name: Ubuntu update
      run:  sudo apt update

    - name: Install Tree
      run:
        sudo apt install tree

    - name: Tree
      run:
        tree

    - name: Test Perl
      run:
        perl -Idtt/lib -Imicl/lib lib/Svg/Simple.pm
